# colors

colors:
  base:
    white: "#ffffff"
    black: "#0b0b0b"
  baseAdjustSteps: 10
  schemes:
    default:
      brand:       "#fff500"
      accent:      "rgb(56, 188, 25)"
      success:     "hsl(136, 79%, 45%)"
      warning:     "#dae21e"
      danger:      "#e80f0f"
      info:        "#0080ff"
      interactive: "#178ee5"
    alternative:
      brand:       "#0089ff"
      success:     "#4fc970"
      warning:     "#b1b907"
      danger:      "#ea3838"
      info:        "#237cd4"
  schemesAdjustSteps: 5
  metaThemeColor: "#dee600"
  colorGuides: "#ff0080"
  
  
#grid

grid:
  breakpoints:
    xs: 0
    sm: 576
    md: 768
    lg: 992
    xl: 1200
  breakpointsUnit: px
  layoutMinWidth: 320px
  columns: 16
  gutters:
    wrapper: "(xs: 16px, sm: 0, lg: 32px)"
    container: false
    row: false
    col: "(xs: 8px, md: 16px)"
  fixWrapperWidth: "(md, xl)"
  rotateBackMap: false
  
  
#spacers  
  
spacers:
  spacer: 8px
  spacerMap:
    a: "(xs: 1)"
    b: "(xs: 2, sm: 3)"
    c: "(xs: 4)"
    d: "(xs: 6)"
    e: "(xs: 10)"
  defaultMarginY:
    container: false
    row: b
    col: false
  defaultColPadding: false
  
  
#typography  
  
typography:
  fontsInclude:
    Roboto: 400
  fontsGoogle:
    PT Serif: "https://fonts.googleapis.com/css?family=PT+Serif&display=swap"
  fontMain:       Roboto
  fontStyle:      "sans-serif"
  htmlFontSize:   16px
  fontSizeBase:   1rem
  lineHeightBase: 1.5
  fontWeightBase: normal